#开发环境
spring:
  datasource:
    name: info_publishing
    password: xiaoji123
    username: root
    url: jdbc:mysql://localhost:3306/glowworm?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
#reids
redis:
    host: 127.0.0.1
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000